### ISSUE TITLE
How do you give the output shape to a 3 class classification

### ISSUE THREAD

**Issue by Maneeshmohan1** [simongraham/dsf-cnn#14]

**Comment by Maneeshmohan1** [comment]
did you use  in this way  
```
    img = cv2.imread(high + high_dir[x]) 
    h,w,c = img.shape
    img_size = h*w*c
    img_1D_vector = img.reshape(img_size)
    m = np.append(img_1D_vector,0)
```

**Comment by simongraham** [comment]
In the classification model, the number of classes is hard coded as 2[ here](https://github.com/simongraham/dsf-cnn/blob/master/src/model/class_pcam/graph.py#L153). This can be changed directly, or you can set it in `config.py` and set it as a variable in `graph.py` to update dynamically. Of course, with this you should also ensure that the data has the right number of classes.

**Comment by simongraham** [comment]
Please also note with this that we compute the AUC during training [here](https://github.com/simongraham/dsf-cnn/blob/master/src/train.py#L122), which of course is well suited to binary classification. Instead, if you are using more than 2 classes you may want to instead incorporate a different metric during training.
