### ISSUE TITLE
patch_extractor.py

### ISSUE THREAD

**Issue by 1chy30** [simongraham/dsf-cnn#16]
Patch_extractor.py is a core code for extracting patches?The specific data set extraction patch should be implemented through the code written by oneself.

**Comment by simongraham** [comment]
Hi @1chy30 ,

Yes exactly. I will include a basic script to show how this is used for extracting the patches and will mention in this issue.

**Comment by simongraham** [comment]
@1chy30 you can now find the patch extraction script [here](https://github.com/simongraham/dsf-cnn/blob/master/src/extract_patches.py).
