### ISSUE TITLE
AssertionError:    assert batch_size <= len(ds)

### ISSUE THREAD

**Issue by Alllllen** [simongraham/dsf-cnn#20]
Hi , I got some error. Do you have any idea ? thanks
![image](https://user-images.githubusercontent.com/38940305/124377458-9b393480-dcde-11eb-8bbe-64aacb2ed4e1.png)

**Comment by bushra-tayyaba** [comment]
I have got the same error. Have you found any solution for this?

**Comment by shianewelin** [comment]
No, did you find a solution for this?

**Comment by simongraham** [comment]
Hi - this error normally comes from the path to the data not being correct. Can you please double check the path to your data. This is specified in the config file [here](https://github.com/simongraham/dsf-cnn/blob/master/src/config.py#L38).
