### ISSUE TITLE
tensorflow version Compatibility

### ISSUE THREAD

**Issue by bushra-tayyaba** [simongraham/dsf-cnn#23]
I am using colab for experimentation. Here i cannot install tensorflow-gpu==1.12.0. Is there any way to the script with a newer version of TensorFlow? or Can you suggest me something regarding this issue?

**Comment by simongraham** [comment]
We only support with the specified library versions as this code repository is not actively maintained. I'm sure you could make it work with updated versions of TensorFlow. You are welcome to make a pull request for that and I am happy to review it :)
