### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by faraperu** [simongraham/dsf-cnn#4]
Dear Simon ,
I recently rectified the previous issues thanks for your feedback.
After solving the environment and hardware issues  get this error. i will be glad to get your advice.
![image](https://user-images.githubusercontent.com/34961521/87905694-c6a61d80-ca93-11ea-9d1d-29f00d0bba40.png)

**Comment by simongraham** [comment]
Hi @faraperu - this will be because the path is incorrect to the data. Please double check that and let me know if that solves your issue :+1:

**Comment by faraperu** [comment]
Hi@simongraham  I have corrected it and still the same error. could it be a problem with the batch size or its because of my data. am using this dataset" https://www.kaggle.com/paultimothymooney/breast-histopathology-images "

**Comment by faraperu** [comment]
![image](https://user-images.githubusercontent.com/34961521/88177836-0fa8ce00-cc5c-11ea-9e46-f4c7366f7161.png)

**Comment by faraperu** [comment]
In debug mode

**Comment by simongraham** [comment]
It appears that you have specified `224x224` as your input size? This would have been specified in `src/opt/`. It seems that the dataset that you are training with takes an input size of `50x50`.So what you will need to do is save each image as a numpy file of size `(HxW)+1`, where the last value is the label (starting from 0). So in your case, the array will be of size 2501. Please cross check this.

**Comment by faraperu** [comment]
Thank you very much once again. let me do that right now.

**Comment by faraperu** [comment]
Is this right?
![image](https://user-images.githubusercontent.com/34961521/88194975-0a567e00-cc72-11ea-84f1-c5d57001033f.png)

**Comment by simongraham** [comment]
It looks right as long as these are the dimensions of your data :)

**Comment by faraperu** [comment]
any suggested link to the preprocesing code that may match your model?

**Comment by simongraham** [comment]
The images were augmented on the fly, which can be seen [here](https://github.com/simongraham/dsf-cnn/blob/master/src/opt/augs.py). Then the images were scaled between 0 and 1 before input to the network. If you have further questions on this, please raise a new issue with the new subject so that we can better track issues.
