### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by xiaoiker** [simongraham/dsf-cnn#6]
Hello,
In the utils/rotation_utils.py line 236 and 237, the for loops are using the same ranges, is this right?

Best.

**Comment by simongraham** [comment]
Hi,

This script is not actually used in this repository. That script, is taken from `www.github.com/tueimage/SE2CNN` that rotates standard 2D filters with bilinear interpolation. I would recommend asking the issue on the respective repo. We will remove the script from this repo to clean it up.
